GET http://localhost:3333/api/livros

###
GET http://localhost:3333/api/livros/24

###
POST http://localhost:3333/api/livros
Content-Type: application/json

{
    "titulo": "Verity",
    "autor": "Colleen Hoover",
    "editora": "Galera Record",
    "ano_publicacao": "2018",
    "isbn": "978-8501117845",
    "quant_total": 10,
    "quant_disponivel": 10,
    "valor_aquisicao": "50.00"
}
###
PUT http://localhost:3333/api/livros/24
Content-Type: application/json

{
    "titulo": "Verity",
    "autor": "Colleen Hoover",
    "editora": "Galera Record",
    "ano_publicacao": "2018",
    "isbn": "978-8501117845",
    "quant_total": 10,
    "quant_disponivel": 10,
    "valor_aquisicao": "60.00"
}

###
DELETE http://localhost:3333/api/livros/4